
service: dog-finder-visual-search

provider:
  name: aws
  runtime: python3.6
  memorySize: 128
  stage: dev
  region: us-east-1

  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource: "arn:aws:dynamodb:us-east-1:983570756921:table/dog-finder"
  - Effect: Allow
    Action:
      - s3:PutObject
      - s3:GetObject
    Resource: "arn:aws:s3:::dog-finder-images/*"


functions:
  hello:
    handler: handler.hello
    layers:
      - ${self:custom.tfLayer}

  vectorize:
    memorySize: 500
    timeout: 300
    handler: vectorize.handler
    layers:
      - ${self:custom.tfLayer}
    events:
      - http:
          path: vectorize
          method: post

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  tfLayer: arn:aws:lambda:us-east-1:347034527139:layer:tf_keras_pillow:5
  pythonRequirements:
    dockerizePip: non-linux
    zip: true

package:
  exclude:
    - node_modules/**